package com.chessplatform.game.api.dto;

import com.chessplatform.chess.Promotion;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.PositiveOrZero;

import java.util.UUID;

public final class GameRequests {

    private GameRequests() {
    }

    /**
     * @param opponentUsername who to play. Username rather than ID because that is what a
     *                         human knows; resolving it is the server's job.
     * @param playAs           WHITE, BLACK, or null for a random draw. Null is the honest
     *                         default — letting the challenger always pick White is a real
     *                         advantage.
     * @param initialSeconds   starting time per player. Null takes the 5+3 default rather
     *                         than rejecting: a challenge form should not force a decision
     *                         about time control on someone who just wants a game.
     * @param incrementSeconds added after each move. Null means the default, 0 means none.
     */
    public record CreateGame(
            @NotBlank String opponentUsername,
            String playAs,
            @Min(10) @Max(86_400) Long initialSeconds,
            @Min(0) @Max(120) Long incrementSeconds) {
    }

    /**
     * @param clientMoveId generated by the client, not the server. That is the whole
     *                     point: the client must be able to retry the same request and
     *                     have it recognised, which is impossible if the server assigns
     *                     the key.
     * @param expectedPly  the ply the client believes it is playing at
     */
    public record SubmitMove(
            @NotNull UUID clientMoveId,
            @PositiveOrZero int expectedPly,
            @NotBlank @Pattern(regexp = "^[a-h][1-8]$") String from,
            @NotBlank @Pattern(regexp = "^[a-h][1-8]$") String to,
            Promotion promotion) {
    }
}
