# The JWT signing key. Generated by Terraform, stored only in Secrets Manager.
#
# Ephemeral + write-only (Terraform 1.11+): the value exists during apply and is sent to AWS,
# but is written to neither the plan nor the state file. A plain random_password would leave
# a key that can mint valid tokens for any user sitting in the state bucket.
ephemeral "random_password" "jwt" {
  length  = 64
  special = false # HS256 needs >= 32 bytes (AuthProperties); 64 alphanumerics is ~380 bits
}

resource "aws_secretsmanager_secret" "jwt" {
  name        = "${var.name}/jwt-secret"
  description = "HS256 signing key for access tokens (chess.auth.jwt-secret)"
  # Deleted immediately on destroy. The default 7-30 day recovery window keeps the NAME
  # reserved, and the next `apply` in the same week fails with "already scheduled for deletion".
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id                = aws_secretsmanager_secret.jwt.id
  secret_string_wo         = ephemeral.random_password.jwt.result
  secret_string_wo_version = 1 # bump to rotate: every existing access token becomes invalid
}
